# Generated by Django 5.0.6 on 2025-03-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_court_courtbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='courtbooking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('premium', 'Premium'), ('gold', 'Gold'), ('silver', 'Silver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='court',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
