# Generated by Django 5.0.3 on 2025-04-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_alter_courtbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='court',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
